### ISSUE TITLE
Spis treści pojawiający się dopiero po drugiej kompilacji

### ISSUE THREAD

**Issue by qamil95** [qamil95/spiewnik#11]
1. Ściągam czyste archiwum ze śpiewnikiem
2. Puszczam pdflatex - powstaje PDF, ale nie ma wygenerowanych zakładek, ani spisu treści na początku
3. Puszczam jeszcze raz - powstaje prawidłowy PDF

Co może być tego przyczyną i jak temu zaradzić? Zakładam jakiś brak wstępnego przeparsowania wszystkich plików, da się to jakoś naprawić?

**Comment by mjenczmyk** [comment]
Tak działa LaTeX, chyba po prostu trzeba kompilować to dwukrotnie - można utworzyć jakiś Makefile czy inny skrypt który będzie kompilować śpiewnik.
