### ISSUE TITLE
Niespójny wygląd chwytów (kursywa)

### ISSUE THREAD

**Issue by qamil95** [qamil95/spiewnik#3]
Enigma\Pastoralka_98.tex oraz Enigma\Piosenka_dla_przyjaciela.tex mają rozjechane chwyty w wygenerowanym PDFie, co widać na załączonym obrazku.
![2020-04-05_18h55_16](https://user-images.githubusercontent.com/19841000/78504684-fe9c8580-776e-11ea-8bcf-885d3d440ebf.png)

Primo, kursywa (w pastorałce E i E7 są napisane normalnie, potem do końca zwrotki kursywą, potem refren normalnie, i w drugiej zwrotce ta sama akcja z kursywą; w Piosence dla przyjaciela Capo III jest kursywą, dalej trzy linijki bez kursywy, cztery linijki kursywą, odstęp i pięć linijek bez kursywy). Od czego to się bierze, skoro w plikach .tex nie ma nic z tym wspólnego? Capo III jest w porządku, ale reszta wydaje się że przez używanie indeksu górnego (^), każda następna linijka do takiej niezakończonej ukośnikami jest zepsuta... Ale to tylko trop, nie znam się na latechu ;)

Secundo, odstępy między chwytami. Najpewniej usunięcie kursywy rozwiąże ten problem, bo o ile "fis gis fis E" mają w miarę ładne odstępy pisane normalną czcionką, o tyle w wersji z kursywą są bardziej "Agis" czy "fisgis", czyli spacje są zjedzone w tym kursywowym tekście. Znowu, nie mam pojęcia czym to może być spowodowane i jakby to można naprawić, toteż zakładam issue :)

**Comment by mjenczmyk** [comment]
~Tryb matematyczny, pewnie te z kursywą są otoczone dolarami (`$`)?~ ~Nie, to nie to jeśli tylko screenshot był z aktualnego mastera.~

To jest tak, że symbol `^` powinien być używany tylko w trybie matematycznym (np. `$E^7$`, a my ignorujemy ostrzeżenia o tym i nie jest dziwnym że coś się wykrzacza. Dodatkowo tryb matematyczny jest domyślnie pisany kursywą, polecenie `\mathrm{E^7}` pozwala to obejść.

Więc rozwiązanie jest znane, pytanie czy chcemy zawsze pisać tak rozwlekle, czy zmodyfikować jakoś środowisko `chord` (ja bym uderzał w tą drugą opcję).

**Comment by qamil95** [comment]
Zdecydowanie, jeśli nie da się w prosty sposób tego dokonać zostając przy tym zastrzeżonym symbolu, można go zmienic też na inny ;)

**Comment by qamil95** [comment]
W komentarzach do #6 dyskutujemy nad rozwiązaniem, generalnie najprostszą opcją jest chyba dorzucenie do github action czegoś (skrypt, regex, cokolwiek) co podmieni każde E^7 na \mathrm{E^7} przed stworzeniem finałowej paczki. Na repo trzymamy nadal "czystą" wersję.

**Comment by qamil95** [comment]
I tak też zostało to zrobione, PR #20 ma już dodany step, który powoduje że output ma ^ bez trybu matematycznego.
